README.md

Thanks for contributing. To speed up the process of reviewing your pull request
please provide us with:
* A short explanation of the proposed change:
* An explanation of the use cases your change enables:
Please confirm the following:

s/biweekly/weekly - Happens weekly now?

---

README.md

Updates the Zoom link for the Working Group meeting

Update WG Zoom link

---

STYLEGUIDE.md

Implements [RFC0016](https://github.com/paketo-buildpacks/rfcs/blob/main/accepted/0016-programming-style-guide.md)

Adds STYLEGUIDE.md

---

TEAMS.md

Adds Rust and Web Servers teams

---

README.md

Link to our roadmap in this README!
Resolves #18

Adds link to roadmap

---

GOVERNANCE.md

resolves https://github.com/paketo-buildpacks/community/issues/16

fix broken link

---

ROADMAP.md

This is a first pass at the current state of the 2021 Roadmap with links to RFCs and issues where I was able to find them. We should iterate on this constantly to ensure we track everything that we can and also keep it up-to-date as statuses change.
Resolves #20.

First pass at ROADMAP.md

---

ROADMAP.md

It looks like poetry is pretty popular. We could look into adding a poetry buildpack as part of the
Python language-family buildpack.
Feature request Issue: https://github.com/paketo-community/python/issues/196

Can we aim to support poetry on python?

---

TEAMS.md

Updates the teams with their current membership. This also starts to track contributors for each subteam. Finally, it moves @joshzarrabi and @mdelillo to emeritus positions across all of the subteams they worked in.

Updates teams with latest membership

---

TEAMS.md

All teams that @dwillist was previous active on have voted that he be moved to retirement in an emeritus position. His status has been updated on the team board to reflect that change.

Moves @dwillist to Emeritus status

---

ROADMAP.md

Marks RFCs / Issues that are complete. Also, includes new issues that fall under existing roadmap items.

Updates roadmap with latest status

---

TEAMS.md

@ForestEckhardt was voted in as the newest maintainer for the Tooling team. This updates that information in the Teams listing.

Promotes @ForestEckhardt to Tooling maintainer

---

TEAMS.md

@kvedurmu has requested to retire from the Content team. His status has been updated to reflect his new Emeritus position.

Moves @kvedurmu to emeritus maintainer for Content team

---

ROADMAP.md

References new issues opened in the `rfcs` repo.

Updates ROADMAP

---

TEAMS.md

https://github.com/orgs/paketo-buildpacks/teams/java-buildpacks/discussions/1

@nebhale -> Emeritus on the Java Team

---

TEAMS.md

https://github.com/orgs/paketo-buildpacks/teams/utilities/discussions/3

@nebhale -> Emeritus on the Utilities Team

---

TEAMS.md

https://github.com/orgs/paketo-buildpacks/teams/java-buildpacks/discussions/2

@twoseat -> Emeritus on the Java Team

---

TEAMS.md

Adds @dmikusa-pivotal to @paketo-buildapcks/utilities-maintainers
Moves @twoseat to utilties team emeritus
https://github.com/orgs/paketo-buildpacks/teams/utilities/discussions/1
https://github.com/orgs/paketo-buildpacks/teams/utilities/discussions/2

Utilities team updates

---

TEAMS.md

Updates Content subteam membership

---

TEAMS.md

The Dependencies and Stacks teams have been updated to represent their current membership status.

Updates Dependencies and Stacks teams with current membership

---

TEAMS.md

Promotes @fg-j to Tooling Maintainer

---

TEAMS.md

@thitch97 was promoted into a Contributor role on the Dependencies subteam. This updates the TEAMS.md to reflect that.

Adds @thitch97 to Dependencies Contributors team

---

TEAMS.md

Promotes @andymoe to Content Maintainer

---

TEAMS.md

@AccraZed was nominated and approved as a contributor to the Node.JS subteam in this discussion: https://github.com/orgs/paketo-buildpacks/teams/nodejs-contributors/discussions/1.

Adds @AccraZed as Node.js Contributor

---

TEAMS.md

@arjun024 was voted in as a contributor for [Stacks](https://github.com/orgs/paketo-buildpacks/teams/stacks/discussions/5) and [Dependencies](https://github.com/orgs/paketo-buildpacks/teams/dependencies/discussions/6).

Adds @arjun024 as a contributor for Stacks and Dependencies

---

TEAMS.md

Codifies the vote taken by @ryanmoran and @ekcasey on 09/21/2021

Promotes @dmikusa-pivotal to the Steering Committee 🎉

---

TEAMS.md

Promotes @TisVictress to Content Maintainer

---

TEAMS.md

Updates team memberships

---

TEAMS.md

https://github.com/orgs/paketo-buildpacks/teams/php/discussions/3
https://github.com/orgs/paketo-buildpacks/teams/python/discussions/1

Teams: move myself from php/python maintainer to contrib

---

TEAMS.md

Adds @robdimsdale as Python contributor

---

STYLEGUIDE.md

Per discussion about log streaming in the [1/25/22 Paketo Working Group meeting](https://docs.google.com/document/d/1V1jtZmjpivMsWdoYOrGlaK4exoIezn2r4Lf3XcPxduQ/edit?usp=sharing), I've added some logging guidelines to the style guide.

Add logging section to style guide

---

TEAMS.md

In accordance with the vote: https://github.com/orgs/paketo-buildpacks/teams/utilities/discussions/5
Signed-off-by: Daniel Mikusa <dmikusa@vmware.com>

Moves David from contributors to maintainers team for Utilities

---

TEAMS.md

Moves @andymoe to Emeritus Content Maintainer

---

TEAMS.md

Adds @joshuatcasey as Python Contributor

---

TEAMS.md

Adds @TisVictress to Go Contributors

---

TEAMS.md

Adds @joshuatcasey as .NET Core contributor

---

TEAMS.md

Promotes @sophiewigmore to PHP Maintainer

---

TEAMS.md

Adds @robdimsdale as PHP Contributor

---

TEAMS.md

Adds @ryanmoran as Stacks Contributor

---

TEAMS.md

Adds @TisVictress as Node.js Contributor

---

TEAMS.md

Adds @TisVictress as Web Servers Contributor

---

TEAMS.md

Adds @robdimsdale as a Ruby Contributor

---

.github/CODEOWNERS
GOVERNANCE.md

- Makes steering team CODEOWNERS of the governance document

Changes maintainer nomination criteria to reflect reality

---

ROADMAP.md

Updates ROADMAP.md to reflect current priorities and progress

Roadmap Updates

---

ROADMAP.md

Adds RFC0047 to ROADMAP.md

---

TEAMS.md

Adds @joshuatcasey as PHP Contributor

---

TEAMS.md

Promotes @robdimsdale to Ruby Maintainer

---

TEAMS.md

Promotes @joshuatcasey to Python Maintainer

---

TEAMS.md

Promotes @TisVictress to Node.js Maintainer

---

ROADMAP.md

Removes completed roadmap items

---

TEAMS.md

Promotes @robdimsdale to Stacks Maintainer

---

TEAMS.md

Adds @fg-j as Stacks Contributor

---

TEAMS.md

Moves @dmikusa-pivotal to Emeritus Maintainers list

---

TEAMS.md

Adds @robdimsdale to Builders Contributors team

---

README.md

Signed-off-by: David Espejo <daespejo@vmware.com>
Adding:
* Guidelines on how to contribute (for this one to work properly, the referenced board should be made visible by an org owner, after review)
* Mailing list link
* New Zoom links for WG and Java team meetings

Add mailing list, new meetings links

---

ADOPTERS.md

Signed-off-by: David Espejo <daespejo@vmware.com>
Adding Fly.io to the ADOPTERS list

Add Fly to ADOPTERS

---

TEAMS.md

Adds @robdimsdale as Contributor to the Dependencies Team

---

ADOPTERS.md

Signed-off-by: David Espejo <daespejo@vmware.com>
Adding Doximity and Randoli as new adopters to the list

Add new adopters

---

TEAMS.md

Adds @joshuatcasey as Dependencies Contributor

---

ADOPTERS.md

Signed-off-by: David Espejo <daespejo@vmware.com>

Add Porter to ADOPTERS

---

TEAMS.md

Promotes @robdimsdale to Tooling Maintainer

---

TEAMS.md

Moves @fg-j to Emeritus Content Maintainer

---

TEAMS.md

Adds @robdimsdale as Builders maintainer

---

TEAMS.md

Moves @ekcasey, @dumez-k, and @fg-j to Builders Emeritus member status

---

TEAMS.md

Adds @TisVictress as PHP Contributor

---

TEAMS.md

Adds @robdimsdale as Dependencies Maintainer

---

TEAMS.md

Adds @c0d1ngm0nk3y as Node.js contributor

---

TEAMS.md

I shortened my Github handle a while back. This change updates the doc to my new handle.
Signed-off-by: Daniel Mikusa <dan@mikusa.com>

Updates my Github handle

---

TEAMS.md

Adds @robdimsdale to the Node.js contributors team

---

TEAMS.md

Updates Java contributors

---

GOVERNANCE.md
STEERING.md

With the acceptance of RFC 0054, there is a formal process for Steering Committee elections. This PR adds that information to the community repo.

Document RFC 0054

---

TEAMS.md

See this discussion for the promotion details https://github.com/orgs/paketo-buildpacks/discussions/187

Add @anthonydahanne as a Java Mainatiner

---

README.md

doc: add Node.js meeting

---

README.md

Add the google calendar link for the Node.js subteam meeting

doc: add calendar link for the Node.js meeting

---

TEAMS.md

Remove @TisVictress from maintainer and contributor teams

---

TEAMS.md

Remove @brayanhenao from maintainer and contributor teams

---

TEAMS.md

Remove @thitch97 from maintainer and contributor teams

---

README.md

Updated Zoom links
Moving meeting to the Linux Foundation's LFX platform required generating new Zoom meeting links.  The links for the Tuesday meeting, Wednesday meeting and Java subteam meeting have been updated in the README.

Update Zoom Links
